version: '2'

services:
  fluentd:
    #build: .
    image: berndinox/fluentd-pushover
    hostname: fluentd
    expose:
      - "24224"
    volumes:
      - ./fluent.conf:/fluentd/etc/fluent.conf
    restart: always
    networks:
      logs:
        ipv4_address: 10.0.0.10

networks:
  logs:
    driver: bridge
    ipam:
      driver: default
      config:
      - subnet: 10.0.0.0/24
        gateway: 10.0.0.1
